/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/template_mypluginPanel.java to edit this template
 */
package nb.module.tooling.sqlite;

import java.awt.Desktop;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JFileChooser;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;
import org.openide.util.NbPreferences;

final class SQLitePanel extends javax.swing.JPanel {

    private final SQLiteOptionsPanelController controller;

    SQLitePanel(SQLiteOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl01 = new javax.swing.JLabel();
        txtSqliteStudioPath = new javax.swing.JTextField();
        btnLocateSqliteStudio = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl02 = new javax.swing.JLabel();
        btnGoToWebsite = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        org.openide.awt.Mnemonics.setLocalizedText(lbl01, org.openide.util.NbBundle.getMessage(SQLitePanel.class, "SQLitePanel.lbl01.text")); // NOI18N

        txtSqliteStudioPath.setText(org.openide.util.NbBundle.getMessage(SQLitePanel.class, "SQLitePanel.txtSqliteStudioPath.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnLocateSqliteStudio, org.openide.util.NbBundle.getMessage(SQLitePanel.class, "SQLitePanel.btnLocateSqliteStudio.text")); // NOI18N
        btnLocateSqliteStudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocateSqliteStudioActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        org.openide.awt.Mnemonics.setLocalizedText(lbl02, org.openide.util.NbBundle.getMessage(SQLitePanel.class, "SQLitePanel.lbl02.text")); // NOI18N
        jPanel1.add(lbl02);
        lbl02.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(SQLitePanel.class, "SQLitePanel.lbl02.AccessibleContext.accessibleName")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnGoToWebsite, org.openide.util.NbBundle.getMessage(SQLitePanel.class, "SQLitePanel.btnGoToWebsite.text")); // NOI18N
        btnGoToWebsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToWebsiteActionPerformed(evt);
            }
        });
        jPanel1.add(btnGoToWebsite);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSqliteStudioPath, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLocateSqliteStudio))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSqliteStudioPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl01)
                    .addComponent(btnLocateSqliteStudio))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocateSqliteStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocateSqliteStudioActionPerformed
        JFileChooser dialog = new JFileChooser();
        int result = dialog.showOpenDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            txtSqliteStudioPath.setText(dialog.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnLocateSqliteStudioActionPerformed

    private void btnGoToWebsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToWebsiteActionPerformed
        if(Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)){
            try {
                Desktop.getDesktop().browse(new URI("https://sqlitestudio.pl/"));
            } catch (Exception exception) {
                NotifyDescriptor descriptor = new NotifyDescriptor.Message("ERROR: " + exception.getMessage(), NotifyDescriptor.ERROR_MESSAGE);
                DialogDisplayer.getDefault().notify(descriptor);
            }
        } else {
            NotifyDescriptor descriptor = new NotifyDescriptor.Message("Web browser settings are invalid.\nPlease provide valid browser selection in 'Tools > Options > General [section]'.", NotifyDescriptor.WARNING_MESSAGE);
            DialogDisplayer.getDefault().notify(descriptor);
        }
    }//GEN-LAST:event_btnGoToWebsiteActionPerformed

    void load() {
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(SQLitePanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(SQLitePanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
        String sqlite_studio_path = NbPreferences.forModule(SQLitePanel.class).get("sqlite_studio_path", "");
        txtSqliteStudioPath.setText(sqlite_studio_path);
    }

    void store() {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(SQLitePanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(SQLitePanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
        NbPreferences.forModule(SQLitePanel.class).put("sqlite_studio_path", txtSqliteStudioPath.getText().trim());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoToWebsite;
    private javax.swing.JButton btnLocateSqliteStudio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl01;
    private javax.swing.JLabel lbl02;
    private javax.swing.JTextField txtSqliteStudioPath;
    // End of variables declaration//GEN-END:variables
}
