/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/visualPanel.java to edit this template
 */
package nb.module.tooling.sqlite;

import javax.swing.JPanel;
import javax.swing.JTextField;

public final class SQLiteDtabaseVisualPanel1 extends JPanel {

    /**
     * Creates new form SQLiteDtabaseVisualPanel1
     */
    public SQLiteDtabaseVisualPanel1() {
	initComponents();
    }

    @Override
    public String getName() {
	return "Creante a new SQLite Database file.";
    }
    
    public JTextField targetDir() {return txtTargetDir;}
    public JTextField databaseName() {return txtDatabaseName;}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTargetDir = new javax.swing.JTextField();
        txtDatabaseName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblTargetPath = new javax.swing.JLabel();
        lblDatabaseNAme = new javax.swing.JLabel();

        txtTargetDir.setEditable(false);
        txtTargetDir.setText(org.openide.util.NbBundle.getMessage(SQLiteDtabaseVisualPanel1.class, "SQLiteDtabaseVisualPanel1.txtTargetDir.text")); // NOI18N

        txtDatabaseName.setText(org.openide.util.NbBundle.getMessage(SQLiteDtabaseVisualPanel1.class, "SQLiteDtabaseVisualPanel1.txtDatabaseName.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTargetDir)
                    .addComponent(txtDatabaseName, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTargetDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDatabaseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        org.openide.awt.Mnemonics.setLocalizedText(lblTargetPath, org.openide.util.NbBundle.getMessage(SQLiteDtabaseVisualPanel1.class, "SQLiteDtabaseVisualPanel1.lblTargetPath.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblDatabaseNAme, org.openide.util.NbBundle.getMessage(SQLiteDtabaseVisualPanel1.class, "SQLiteDtabaseVisualPanel1.lblDatabaseNAme.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTargetPath, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDatabaseNAme, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTargetPath)
                .addGap(18, 18, 18)
                .addComponent(lblDatabaseNAme)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(382, 382, 382))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDatabaseNAme;
    private javax.swing.JLabel lblTargetPath;
    private javax.swing.JTextField txtDatabaseName;
    private javax.swing.JTextField txtTargetDir;
    // End of variables declaration//GEN-END:variables
}
